################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../src/objs/accelerators_bvh.o \
../src/objs/accelerators_grid.o \
../src/objs/accelerators_kdtreeaccel.o \
../src/objs/cameras_environment.o \
../src/objs/cameras_orthographic.o \
../src/objs/cameras_perspective.o \
../src/objs/core_api.o \
../src/objs/core_camera.o \
../src/objs/core_diffgeom.o \
../src/objs/core_error.o \
../src/objs/core_fileutil.o \
../src/objs/core_film.o \
../src/objs/core_filter.o \
../src/objs/core_floatfile.o \
../src/objs/core_geometry.o \
../src/objs/core_imageio.o \
../src/objs/core_integrator.o \
../src/objs/core_intersection.o \
../src/objs/core_light.o \
../src/objs/core_material.o \
../src/objs/core_memory.o \
../src/objs/core_montecarlo.o \
../src/objs/core_parallel.o \
../src/objs/core_paramset.o \
../src/objs/core_parser.o \
../src/objs/core_pbrtlex.o \
../src/objs/core_pbrtparse.o \
../src/objs/core_primitive.o \
../src/objs/core_probes.o \
../src/objs/core_progressreporter.o \
../src/objs/core_quaternion.o \
../src/objs/core_reflection.o \
../src/objs/core_renderer.o \
../src/objs/core_rng.o \
../src/objs/core_sampler.o \
../src/objs/core_scene.o \
../src/objs/core_sh.o \
../src/objs/core_shape.o \
../src/objs/core_shrots.o \
../src/objs/core_spectrum.o \
../src/objs/core_stdafx.o \
../src/objs/core_targa.o \
../src/objs/core_texture.o \
../src/objs/core_timer.o \
../src/objs/core_transform.o \
../src/objs/core_volume.o \
../src/objs/film_image.o \
../src/objs/filters_box.o \
../src/objs/filters_gaussian.o \
../src/objs/filters_mitchell.o \
../src/objs/filters_sinc.o \
../src/objs/filters_triangle.o \
../src/objs/integrators_ambientocclusion.o \
../src/objs/integrators_diffuseprt.o \
../src/objs/integrators_dipolesubsurface.o \
../src/objs/integrators_directlighting.o \
../src/objs/integrators_emission.o \
../src/objs/integrators_glossyprt.o \
../src/objs/integrators_igi.o \
../src/objs/integrators_irradiancecache.o \
../src/objs/integrators_path.o \
../src/objs/integrators_photonmap.o \
../src/objs/integrators_single.o \
../src/objs/integrators_useprobes.o \
../src/objs/integrators_whitted.o \
../src/objs/lights_diffuse.o \
../src/objs/lights_distant.o \
../src/objs/lights_goniometric.o \
../src/objs/lights_infinite.o \
../src/objs/lights_point.o \
../src/objs/lights_projection.o \
../src/objs/lights_spot.o \
../src/objs/main_pbrt.o \
../src/objs/materials_glass.o \
../src/objs/materials_kdsubsurface.o \
../src/objs/materials_matte.o \
../src/objs/materials_measured.o \
../src/objs/materials_metal.o \
../src/objs/materials_mirror.o \
../src/objs/materials_mixmat.o \
../src/objs/materials_plastic.o \
../src/objs/materials_shinymetal.o \
../src/objs/materials_substrate.o \
../src/objs/materials_subsurface.o \
../src/objs/materials_translucent.o \
../src/objs/materials_uber.o \
../src/objs/renderers_aggregatetest.o \
../src/objs/renderers_createprobes.o \
../src/objs/renderers_metropolis.o \
../src/objs/renderers_samplerrenderer.o \
../src/objs/renderers_surfacepoints.o \
../src/objs/samplers_adaptive.o \
../src/objs/samplers_bestcandidate.o \
../src/objs/samplers_halton.o \
../src/objs/samplers_lowdiscrepancy.o \
../src/objs/samplers_random.o \
../src/objs/samplers_stratified.o \
../src/objs/shapes_cone.o \
../src/objs/shapes_cylinder.o \
../src/objs/shapes_disk.o \
../src/objs/shapes_heightfield.o \
../src/objs/shapes_hyperboloid.o \
../src/objs/shapes_loopsubdiv.o \
../src/objs/shapes_nurbs.o \
../src/objs/shapes_paraboloid.o \
../src/objs/shapes_sphere.o \
../src/objs/shapes_trianglemesh.o \
../src/objs/textures_bilerp.o \
../src/objs/textures_checkerboard.o \
../src/objs/textures_constant.o \
../src/objs/textures_dots.o \
../src/objs/textures_fbm.o \
../src/objs/textures_imagemap.o \
../src/objs/textures_marble.o \
../src/objs/textures_mix.o \
../src/objs/textures_scale.o \
../src/objs/textures_uv.o \
../src/objs/textures_windy.o \
../src/objs/textures_wrinkled.o \
../src/objs/volumes_exponential.o \
../src/objs/volumes_homogeneous.o \
../src/objs/volumes_volumegrid.o 


# Each subdirectory must supply rules for building sources it contributes

